title = "Bradley Reynolds"
languageCode = "en-us"
defaultContentLanguage = "en"
timeZone = "America/Chicago"
copyright = "© 2022-present, Bradley Reynolds"

theme = "PaperMod"

baseURL = 'https://bradley.dog/'
enableRobotsTXT = true
paginate = 15

[params]
description = "Bradley Reynolds' site"
defaultTheme = "auto"
showReadingTime = true
showCodeCopyButtons = true
showPostNavLinks = true
env = "development"
keywords = ["oss", "foss"]

# Shown on the home page
socialIcons = [
  { name = "github", url = "https://github.com/shenanigansd" },
  { name = "python", url = "https://discuss.python.org/u/shenanigansd/summary" },
  { name = "stackoverflow", url = "https://stackoverflow.com/users/19147567/bradley-reynolds"},
]

[params.schema]
publisherType = "Person"
sameAs = [
  "https://github.com/shenanigansd",
  "https://discuss.python.org/u/shenanigansd/summary",
  "https://stackoverflow.com/users/19147567/bradley-reynolds",
  "https://pypi.org/user/bradleyreynolds/",
  "https://readthedocs.org/profiles/shenanigansd/",
]

# Configure the home page
[params.profileMode]
enabled = true
title = "Hi, I'm Bradley"
subtitle = "I'm just a dog trying to help people out"
imageUrl = "/profile-image.jpeg"

[params.assets]
disableFingerprinting = true
